### ISSUE TITLE
pMusic has missing icons when called by puppy_event_manager

### ISSUE THREAD

**Issue by peabee** [puppylinux-woof-CE/woof-CE#3568]
slacko-8.2.2-264

@01micko @zigbert 

when called via the code in /usr/local/pup_event/drive_all 
when triggered by HOTPLUGNOISY=true in /etc/eventmanager
all of pMusic icons are missing

![screenshot](https://user-images.githubusercontent.com/5926865/199067807-68cf95f4-084f-4696-af36-aa507203081a.png)

**Comment by zigbert** [comment]
This is pup_event calling defaultcdplayer which again is calling pmusic_CD which probably is executing 
`/usr/local/pmusic/pmusic -j -p '.CD' -c -T Gtk`
Works here in Slacko 7. Is there an iso I can test with this issue?

**Comment by peabee** [comment]
Hi - thanks for replying....
I got slacko-8.2.2-264
from
https://github.com/puppylinux-woof-CE/woof-CE/actions/runs/3262143816

direct link:
https://github.com/puppylinux-woof-CE/woof-CE/suites/8802359458/artifacts/400327628

**Comment by peabee** [comment]
Sorry - the links above have expired and there is now no build of slacko-8.2.2 available. It may reappear tomorrow 02-11-22 I understand.

**Comment by zigbert** [comment]
Tested the S15Pup64-22.11-RC.
First boot - icons are there...

![Screenshot](https://user-images.githubusercontent.com/5928708/199350094-6032b713-4672-4480-badc-5f441ceb7a4a.png)

**Comment by zigbert** [comment]
Fixed for both GTK2/3 in #[8a7d974](https://github.com/puppylinux-woof-CE/woof-CE/commit/8a7d974392bbc599c14cdb857d436378eba3e161)

**Comment by zigbert** [comment]
Also fixed missing icons in the Podcast frontend

**Comment by zigbert** [comment]
Please test to verify. Thank you!

**Comment by peabee** [comment]
> Please test to verify. Thank you!

Thanks for your help - but sorry, no, the recent commits did not fix the problem.....

I downloaded Woof-CE and copied the .cd and .podcast frontends into /usr/local/pmusic/frontends

Inserted a cd and the pMusic window appeared without icons (the startup splash also shows "washed out")

The problem only occurs when a cd is inserted. If I click on the sr0 disk icon on the desktop, pMusic starts with icons showing correctly.

The problem also only occurs when HOTPLUGNOISY=true in /etc/eventmanager

**Comment by peabee** [comment]
@zigbert 
I have been trying to do some diagnosis of what the difference is between calling pmusic cdplayer from the event manager on cd insertion versus clicking the sr0 desktop icon.....

I can produce diagnostics by putting a "write to file" into the code - vis. 
echo {info} > file.txt

and this shows that one difference is that pwd is
/ when called by the event manager on cd insertion
/root when called by clicking the desktop sr0 icon

I could do with some advice about which code-file to put the diagnostics into and what info to capture???
Many thanks
Peter

**Comment by peabee** [comment]
> I could do with some advice about which code-file to put the diagnostics into and what info to capture??? Many thanks Peter

**Comment by zigbert** [comment]
@peabee 
Sorry for the absence - just too much atm... 
Not much time for digging, but some brief thoughts...

- Does it help to change cdplayer i Puppyapps from pmusic_CD to pmusic
  --> Yes means issue is in .CD frontend
- In /usr/local/pmusic/func the GTK-theme is set in function 'set_gtk' in line 466.
  --> It would be informative to see if $APPDIR, $WORKDIR and $HOME has correct values when running this code
- Since pwd is different it might help to execute 'cd /root/' before running pMusic.

**Comment by peabee** [comment]
Hi @zigbert 
Thanks for the advice - which I've tried but........
- change of defaultcdplayer did not help
- echo "$APPDIR, $WORKDIR and $HOME" gave: /usr/local/pmusic, /root/.pmusic/tmp and /root
- putting cd /root into defaultcdplayer did not help

If you think of anything else to check please let me know - in the meantime I've set HOTPLUGNOISY=false

**Comment by peabee** [comment]
Problem made to "go away" by patching /usr/local/pup_event/drive_all in local builds to not call pmusic for cd's
